#!/bin/bash

# Modified from https://github.com/ChimeraOS/chimera-data/blob/1321907ffe4f453cbfe80badb841f9958e54a6d4/compat/tool-stub.tpl

# prevent premature download triggered by Steam
if echo "$@" | grep "d3ddriverquery64.exe" > /dev/null; then
	exit
fi

DEFAULT_TOOL_DIR="${TOOL_FILE%.tar.*}"

PROGRESS_PIPE=$(mktemp /tmp/armada-tool-downloader-XXXXXX)

mkdir -p $TOOLS_DIR

pushd "$TOOLS_DIR"
rm -f "$TOOL_FILE"
curl -L -O $TOOL_URL -# 2>&1 | \
  stdbuf -oL tr '\r' '\n' | \
  grep --color=auto --line-buffered -oP '[0-9]*+(?=.[0-9])' > "$PROGRESS_PIPE" &
curl_pid="$!"

splash_pid=0
if [ -e /usr/bin/chimera-splash ] ; then
	/usr/bin/chimera-splash --tool "$TOOL_DIR" --pipe-file "$PROGRESS_PIPE" &
	splash_pid="$!"
fi

wait $curl_pid
curl_exit=$?

test $splash_pid || kill -9 $splash_pid

if [ $curl_exit -ne 0 ]; then
	if [ -e "$TOOLS_DIR/$TOOL_DIR/$TOOL_CMD" ]; then
		echo "download failed, using existing $TOOL_DIR"
		popd
		exec "$TOOLS_DIR/$TOOL_DIR/$TOOL_CMD" $@
	else
		echo "download failed and no existing tool found"
		exit
	fi
fi

if ! echo "$TOOL_MD5SUM $TOOL_FILE" | md5sum --status -c; then
	if [ -e "$TOOLS_DIR/$TOOL_DIR/$TOOL_CMD" ]; then
		echo "checksum mismatch, using existing $TOOL_DIR"
		popd
		exec "$TOOLS_DIR/$TOOL_DIR/$TOOL_CMD" $@
	else
		echo "checksum mismatch and no existing tool found"
		exit
	fi
fi

rm -rf "$TOOL_DIR"
tar xf "$TOOL_FILE" --transform="s/^${DEFAULT_TOOL_DIR}/${TOOL_DIR}/"
rm "$TOOL_FILE"

if [ "${TOOL_DIR}" = "proton-cachyos-arm64" ]; then
    python3 /usr/share/steam/compatibilitytools.d/proton-cachyos-arm64/patch-proton-cachyos-dxvk-probe.py \
        "${TOOL_DIR}/proton"
fi

popd

exec "$TOOLS_DIR/$TOOL_DIR/$TOOL_CMD" $@