// Keep this feature's initial English copy separate from the existing locales.
// Reviewed translations can be introduced independently of the input service.
const strings = {
  "trackpads.title": "Virtual Trackpads",
  "trackpads.gameModeOnly": "Game Mode only",
  "trackpads.gameModeOnlyDescription": "Restore normal touch in Desktop Mode.",
  "trackpads.autoHide": "Hide automatically",
  "trackpads.hideDelay": "Hide after (seconds)",
  "trackpads.borderWidth": "Outer border (px)",
  "trackpads.backgroundStyle": "Background",
  "trackpads.backgroundDots": "Dots",
  "trackpads.backgroundSolid": "Solid",
  "trackpads.backgroundNone": "None",
  "trackpads.master": "Virtual Trackpads",
  "trackpads.masterDescription": "Turning off restores normal touch.",
  "trackpads.mode": "Trackpad mode",
  "trackpads.modeSimple": "Bottom corners",
  "trackpads.modeCorners": "Four corners",
  "trackpads.modeFloating": "Follow first touch",
  "trackpads.modeHalves": "Split screen",
  "trackpads.modeFullLeft": "Full screen: left",
  "trackpads.modeFullRight": "Full screen: right",
  "trackpads.modeSimpleDescription": "One trackpad in each bottom corner.",
  "trackpads.modeCornersDescription": "Both corners on each side control the same pad.",
  "trackpads.modeFloatingDescription": "Each pad appears where you first touch its half.",
  "trackpads.modeHalvesDescription": "Each half works as a trackpad, with no visuals.",
  "trackpads.modeFullLeftDescription": "The whole screen controls the left trackpad; the right is disabled.",
  "trackpads.modeFullRightDescription": "The whole screen controls the right trackpad; the left is disabled.",
  "trackpads.screenModeSettings": "No visuals. Zone and appearance controls are disabled.",
  "trackpads.left": "Left trackpad",
  "trackpads.right": "Right trackpad",
  "trackpads.zones": "Zones",
  "trackpads.sharedSize": "Size (% of screen height)",
  "trackpads.edgeGap": "Corner offset (px)",
  "trackpads.feedback": "Touch and feedback",
  "trackpads.limitToBounds": "Limit to visible area",
  "trackpads.limitToBoundsDescription": "Pause outside the pad; resume on re-entry.",
  "trackpads.hapticStrength": "Vibration strength (%)",
  "trackpads.borderOpacity": "Border opacity (%)",
  "trackpads.backgroundOpacity": "Background opacity (%)",
  "trackpads.appearance": "Appearance",
  "trackpads.borderRadius": "Roundness (%)",
  "trackpads.dotSize": "Dot size (px)",
  "trackpads.dotGap": "Dot spacing (px)",
  "trackpads.centerIndicator": "Center indicator",
  "trackpads.centerDot": "Show center dot",
  "trackpads.centerDotDescription": "Mark each fixed pad's center while hidden.",
  "trackpads.centerDotSize": "Dot size (px)",
  "trackpads.centerDotOpacity": "Dot opacity (%)",
  "trackpads.blockTouchscreen": "Block touchscreen",
  "trackpads.blockTouchscreenDescription": "Block accidental touches. Restore with buttons or a mouse.",
  "trackpads.selectDeckFirst": "Select Steam Deck controller emulation first.",
  "trackpads.unsupported": "Virtual trackpads are not available on this device.",
  "trackpads.saveError": "Could not update virtual trackpads",
  "trackpads.resetDefaults": "Restore defaults",
  "trackpads.resetDefaultsDescription": "Reset settings and turn trackpads off. Normal touch returns.",
  "trackpads.shortcut": "Toggle shortcut",
  "trackpads.shortcutEnabled": "Enable shortcut",
  "trackpads.shortcutDescription": "Your chosen buttons still reach games. Avoid combinations they use.",
  "trackpads.shortcutButtons": "Button combination",
  "trackpads.shortcutEdit": "Choose shortcut buttons",
  "trackpads.shortcutChoose": "Choose 1–4 different buttons to press together.",
  "trackpads.shortcutButton": "Button",
  "trackpads.shortcutAdd": "Add button",
  "trackpads.shortcutRemove": "Remove last button",
  "trackpads.shortcutActivation": "Activation",
  "trackpads.shortcutImmediate": "Immediate",
  "trackpads.shortcutHold": "Hold for 3 seconds",
  "trackpads.touchscreen": "Touchscreen setup",
  "trackpads.screen": "Trackpad screen",
  "trackpads.screenPrimary": "Primary touchscreen",
  "trackpads.screenSecondary": "Secondary touchscreen",
  "trackpads.screenDescription": "Both pads and their overlay use the selected touchscreen.",
  "trackpads.screenSingle": "No secondary touchscreen detected.",
  "trackpads.cancel": "Cancel",
  "trackpads.save": "Save",
} as const;

export function trackpadText(key: keyof typeof strings): string {
  return strings[key];
}
