# Overrides for unl0kr's default configuration for Armada.
# Per-device rotation property is generated as 90-armada-rotate.conf during initramfs.

[theme]
default=breezy-dark
alternate=breezy-light

[input]
pointer=false
